version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: order_summary_db
    environment:
      POSTGRES_DB: order_summary_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

    api:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: order_summary_api
      environment:
        DATABASE_URL: postgresql://admin:admin@postgres:5432/order_summary_db
      ports:
        - "3000:3000"
      depends_on:
        - postgres
      restart: unless-stopped

volumes:
  postgres_data:
